int compression(char *str);
int decompression(char *open_encr,char *open_key,char *str);
int decompression2(char *open_encr,char *open_key,char *str);
int decompression3(char *open_encr,char *open_key,char *str);
int decompression4(char *open_encr,char *open_key,char *str);
int decompression5(char *open_encr,char *open_key,char *str);
int decompression6(char *open_encr,char *open_key,char *);
int decompression7(char *open_encr,char *open_key,char *str);
char * createarray(int);
char * insert(char *,char);
int operation(int,char *,char *);
int mainmenu();
int unique(char *,char);
int codelength(int);
int compression2(char *,int,char *);
int compression3(char *,int,char *);
int compression4(char *,char *,int);
int compression5(char *,int,char *);
int compression6(char*,int,char*);
int compression7(char*,int,char*);
int preserve_masterarray(char *, int,char *);
int findloc(char,char *,int);
