#!/bin/bash
rm -rf *.o
rm -rf mdc
clear
for var in `ls *.h` `ls *.c`
do
        git add  $var
        git commit
done
git add test
git commit
git add makefile
git commit
clear
if ( make )
then
	echo "Your code is successfully compiled."
	echo -e "Do you want to run the code (y/n)?"
	read choice
	if [ $choice == 'y' ]
	then
		./mdc
		read

	else
		echo "thankyou!!"
	fi 
	

fi
